language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t rahulpargi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rahulpargi/react-test npm test

after_success:
  - docker build -t rahulpargi/client ./client
  - docker build -t rahulpargi/nginx ./nginx
  - docker build -t rahulpargi/server ./server
  - docker build -t rahulpargi/worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push rahulpargi/client
  - docker push rahulpargi/nginx
  - docker push rahulpargi/server
  - docker push rahulpargi/worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-container-web"
  env: "Multicontainerweb-env"
  bucket_name: "elasticbeanstalk-us-east-2-246344753294"
  bucket_path: "multi-container-web"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
